server:
  port: 8082

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:h2:mem:notifydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.streambite.events"

    listener:
      ack-mode: MANUAL

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always